language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt

branch:
  only:
      - staging

env: DJANGO_SETTINGS_MODULE="pur_beurre.settings.travis"

service:
   - postgresql

# command to run tests
script:
   - ./manage.py test
